-- 0002_CreateProduct.sql
-- Creates the products table (backs berryfy.domain.entities.productEntities.product).

CREATE TABLE products 
(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	stock_quantity INTEGER NOT NULL DEFAULT 0,
	image_url TEXT NOT NULL,
	price NUMERIC(18,2) NOT NULL,
	reserved_stock INTEGER NOT NULL DEFAULT 0,
	low_stock_threshold INTEGER NOT NULL DEFAULT 5,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	sku TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
