-- 0003_CreateProduct.sql
-- Creates the Coupons table (backs berryfy.domain.entities.CouponEntities.Coupon).

CREATE TABLE coupons 
	(	
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		description TEXT NOT NULL DEFAULT '',
		discount_amount NUMERIC(18,2),
		minimum_order_amount NUMERIC(18,2),
		is_active BOOLEAN NOT NULL DEFAULT TRUE,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		type INTEGER NOT NULL,
		value NUMERIC(18,2),
		is_for_new_users_only BOOLEAN NOT NULL DEFAULT FALSE
	);