CREATE TABLE shops 
	(
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT,
		logo_url TEXT,
		description TEXT,
		email TEXT,
		phone TEXT,
		address TEXT,
		currency TEXT,
		language TEXT
	);