CREATE TABLE inventory_logs 
	(
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		product_id INTEGER NOT NULL REFERENCES products(id),
		current_stock_quantity INTEGER NOT NULL,
		quantity_changed INTEGER NOT NULL,
		change_type INTEGER NOT NULL,
		reference_id INTEGER NOT NULL,
		reference_type TEXT NOT NULL,
		performed_by_user_id INTEGER REFERENCES "AspNetUsers"("Id"),
		notes TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);